"""followers

Revision ID: 921316dd3af7
Revises: d93756a72796
Create Date: 2019-06-27 12:38:35.855990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921316dd3af7'
down_revision = 'd93756a72796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
